<?php
require_once __DIR__ . '/_bootstrap.php';
require_permission('automations.manage');
require_feature('automations');
$id=(int)($_GET['id']??0); $row=db_fetch('SELECT * FROM automation_rules WHERE tenant_id = ? AND id = ? LIMIT 1',[current_tenant_id(),$id]); if(!$row){http_response_code(404);exit('Automation not found');}
$conditions=json_decode((string)$row['conditions_json'], true) ?: []; $actions=json_decode((string)$row['actions_json'], true) ?: [['type'=>'send_email','target'=>'']];
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check(); db_execute('UPDATE automation_rules SET name=?, trigger_key=?, conditions_json=?, actions_json=?, is_active=?, updated_at = NOW() WHERE id = ? AND tenant_id = ?',[trim((string)$_POST['name']),trim((string)$_POST['trigger_key']),json_encode(['status'=>trim((string)($_POST['status_condition']??''))]),json_encode([['type'=>trim((string)$_POST['action_type']),'target'=>trim((string)($_POST['action_target']??''))]]),(int)($_POST['is_active']??1),$id,current_tenant_id()]); flash_success('Automation updated.'); redirect(APP_URL.'/modules/fieldora/automations.php');}
fieldora_layout_start('Edit Automation','automations'); ?>
<form method="post" class="card form-grid"><?= csrf_field() ?><input name="name" value="<?= e($row['name']) ?>" required><select name="trigger_key"><?php foreach(['booking.created','payment.completed','invoice.sent','job.completed'] as $trigger): ?><option value="<?= e($trigger) ?>"<?= $row['trigger_key']===$trigger?' selected':'' ?>><?= e($trigger) ?></option><?php endforeach; ?></select><input name="status_condition" value="<?= e((string)($conditions['status'] ?? '')) ?>" placeholder="Optional status condition"><select name="action_type"><?php foreach(['send_email','send_sms','send_webhook','update_status','create_task'] as $action): ?><option value="<?= e($action) ?>"<?= (($actions[0]['type'] ?? '')===$action)?' selected':'' ?>><?= e($action) ?></option><?php endforeach; ?></select><input name="action_target" value="<?= e((string)($actions[0]['target'] ?? '')) ?>" placeholder="Action target"><select name="is_active"><option value="1"<?= (int)$row['is_active']===1?' selected':'' ?>>Active</option><option value="0"<?= (int)$row['is_active']===0?' selected':'' ?>>Inactive</option></select><button class="primary-btn" type="submit">Save automation</button></form>
<?php fieldora_layout_end();
