<?php
require_once __DIR__ . '/_bootstrap.php';
require_permission('jobs.manage');
$id=(int)($_GET['id']??0); $row=db_fetch('SELECT * FROM jobs WHERE tenant_id = ? AND id = ? LIMIT 1',[current_tenant_id(),$id]); if(!$row){http_response_code(404);exit('Job not found');}
$users=db_fetchall('SELECT id,name FROM users WHERE tenant_id = ? AND active = 1 ORDER BY name ASC',[current_tenant_id()]);
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check(); $newStatus=trim((string)$_POST['status']); db_execute('UPDATE jobs SET title=?, status=?, scheduled_date=?, start_time=?, end_time=?, assigned_user_id=?, address_line1=?, city=?, state=?, postal_code=?, notes=?, internal_notes=?, updated_at = NOW(), completed_at = CASE WHEN ? = "completed" AND completed_at IS NULL THEN NOW() ELSE completed_at END WHERE id = ? AND tenant_id = ?',[trim((string)$_POST['title']),$newStatus,$_POST['scheduled_date']?:null,$_POST['start_time']?:null,$_POST['end_time']?:null,(int)($_POST['assigned_user_id']??0)?:null,trim((string)($_POST['address_line1']??'')),trim((string)($_POST['city']??'')),trim((string)($_POST['state']??'')),trim((string)($_POST['postal_code']??'')),trim((string)($_POST['notes']??'')),trim((string)($_POST['internal_notes']??'')),$newStatus,$id,current_tenant_id()]); \TrashPanda\Fieldora\Services\WebhookService::queueEvent(current_tenant_id(), $newStatus==='completed' ? 'job.completed' : 'job.updated', ['job_id'=>$id]); flash_success('Job updated.'); redirect(APP_URL.'/modules/fieldora/job_view.php?id='.$id);}
fieldora_layout_start('Edit Job','jobs'); ?>
<form method="post" class="card form-grid"><?= csrf_field() ?><input name="title" value="<?= e($row['title']) ?>" required><select name="status"><?php foreach(['scheduled','in_progress','waiting','completed','canceled'] as $status): ?><option value="<?= e($status) ?>"<?= $row['status']===$status?' selected':'' ?>><?= e($status) ?></option><?php endforeach; ?></select><input name="scheduled_date" type="date" value="<?= e($row['scheduled_date']) ?>"><input name="start_time" type="time" value="<?= e((string)$row['start_time']) ?>"><input name="end_time" type="time" value="<?= e((string)$row['end_time']) ?>"><select name="assigned_user_id"><option value="">Unassigned</option><?php foreach($users as $user): ?><option value="<?= (int)$user['id'] ?>"<?= (int)$row['assigned_user_id']===(int)$user['id']?' selected':'' ?>><?= e($user['name']) ?></option><?php endforeach; ?></select><input name="address_line1" value="<?= e($row['address_line1']) ?>" placeholder="Address"><input name="city" value="<?= e($row['city']) ?>" placeholder="City"><input name="state" value="<?= e($row['state']) ?>" placeholder="State"><input name="postal_code" value="<?= e($row['postal_code']) ?>" placeholder="Postal code"><textarea name="notes"><?= e($row['notes']) ?></textarea><textarea name="internal_notes"><?= e($row['internal_notes']) ?></textarea><button class="primary-btn" type="submit">Save job</button></form>
<?php fieldora_layout_end();
