<?php
require_once __DIR__ . '/_bootstrap.php';
require_permission('payments.view');
use TrashPanda\Fieldora\Services\PaymentService;
$tenantId=current_tenant_id();
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check(); $paymentId=PaymentService::createManualPayment($tenantId,['booking_id'=>(int)($_POST['booking_id']??0)?:null,'invoice_id'=>(int)($_POST['invoice_id']??0)?:null,'customer_id'=>(int)($_POST['customer_id']??0)?:null,'amount'=>(float)($_POST['amount']??0),'payment_method'=>trim((string)($_POST['payment_method']??'manual')),'payment_type'=>trim((string)($_POST['payment_type']??'manual')),'external_reference'=>trim((string)($_POST['external_reference']??''))]); PaymentService::applyPaymentToRecords($paymentId); flash_success('Manual payment recorded.'); redirect(APP_URL.'/modules/fieldora/payment_view.php?id='.$paymentId);}
$bookings=db_fetchall('SELECT id, booking_number FROM bookings WHERE tenant_id = ? ORDER BY created_at DESC LIMIT 50',[$tenantId]); $invoices=db_fetchall('SELECT id, invoice_number FROM invoices WHERE tenant_id = ? ORDER BY created_at DESC LIMIT 50',[$tenantId]); $customers=db_fetchall('SELECT id, CONCAT_WS(" ", first_name, last_name) AS name FROM customers WHERE tenant_id = ? AND deleted_at IS NULL ORDER BY first_name ASC',[$tenantId]);
fieldora_layout_start('Record Payment','payments'); ?>
<form method="post" class="card form-grid"><?= csrf_field() ?><select name="booking_id"><option value="">Booking</option><?php foreach($bookings as $row): ?><option value="<?= (int)$row['id'] ?>"><?= e($row['booking_number']) ?></option><?php endforeach; ?></select><select name="invoice_id"><option value="">Invoice</option><?php foreach($invoices as $row): ?><option value="<?= (int)$row['id'] ?>"><?= e($row['invoice_number']) ?></option><?php endforeach; ?></select><select name="customer_id"><option value="">Customer</option><?php foreach($customers as $row): ?><option value="<?= (int)$row['id'] ?>"><?= e($row['name']) ?></option><?php endforeach; ?></select><input name="amount" type="number" step="0.01" placeholder="Amount" required><select name="payment_method"><option value="cash">Cash</option><option value="check">Check</option><option value="bank_transfer">Bank transfer</option><option value="manual">Manual</option></select><select name="payment_type"><option value="deposit">Deposit</option><option value="full">Full</option><option value="invoice">Invoice</option><option value="manual">Manual</option></select><input name="external_reference" placeholder="Reference"><button class="primary-btn" type="submit">Record payment</button></form>
<?php fieldora_layout_end();
