<?php
require_once __DIR__ . '/_bootstrap.php';
require_permission('bookings.manage');
$tenantId = current_tenant_id();
if ($_SERVER['REQUEST_METHOD'] === 'POST') { csrf_check(); db_insert('services', ['tenant_id'=>$tenantId,'name'=>trim((string)$_POST['name']),'description'=>trim((string)($_POST['description']??'')),'price'=>(float)$_POST['price'],'duration_minutes'=>(int)($_POST['duration_minutes']??0)?:null,'deposit_mode'=>trim((string)($_POST['deposit_mode']??'none')),'deposit_value'=>(float)($_POST['deposit_value']??0),'is_active'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]); flash_success('Service added.'); redirect($_SERVER['REQUEST_URI']); }
$search = trim((string) ($_GET['search'] ?? ''));
$rows = db_fetchall('SELECT * FROM services WHERE tenant_id = ? AND (? = "" OR name LIKE ? OR description LIKE ?) ORDER BY sort_order ASC, name ASC', [$tenantId, $search, '%' . $search . '%', '%' . $search . '%']);
$showTour = tenant_setting('tour_' . (int) (current_user()['id'] ?? 0) . '_services', '0') !== '1';
fieldora_layout_start('Services', 'services'); ?>
<?php if ($showTour): ?><section class="card" style="margin-bottom:20px;"><h3>Services page tour</h3><p class="muted">Add your first service here, then edit it for duration, deposits, descriptions, and pricing details. The booking page pulls directly from this list.</p><div class="topbar-actions"><a class="primary-btn" href="<?= e(APP_URL) ?>/modules/fieldora/tour.php?tour=services&done=1">Got it</a><a class="ghost-link" href="<?= e(APP_URL) ?>/modules/fieldora/tour.php?tour=services&done=1">Skip</a></div></section><?php endif; ?>
<form method="post" class="card form-grid"><?= csrf_field() ?><input name="name" placeholder="Service name" required><input name="price" type="number" step="0.01" placeholder="Price" required><input name="duration_minutes" type="number" placeholder="Duration minutes"><select name="deposit_mode"><option value="none">No deposit</option><option value="percent">Percent</option><option value="fixed">Fixed</option></select><input name="deposit_value" type="number" step="0.01" placeholder="Deposit value"><textarea name="description" placeholder="Description"></textarea><button class="primary-btn" type="submit">Add service</button></form>
<form method="get" class="card form-grid" style="margin-top:20px;"><input name="search" value="<?= e($search) ?>" placeholder="Search services"><button class="primary-btn" type="submit">Filter</button></form>
<section class="table-wrap" style="margin-top:20px;"><table><thead><tr><th>Name</th><th>Price</th><th>Duration</th><th>Deposit</th><th></th></tr></thead><tbody><?php if ($rows === []): ?><tr><td colspan="5">No services yet. Add your first service above so customers have something to book.</td></tr><?php else: ?><?php foreach ($rows as $row): ?><tr><td><a href="<?= e(APP_URL) ?>/modules/fieldora/service_view.php?id=<?= (int)$row['id'] ?>"><?= e($row['name']) ?></a></td><td>$<?= number_format((float)$row['price'],2) ?></td><td><?= e((string)$row['duration_minutes']) ?></td><td><?= e($row['deposit_mode']) ?> <?= e((string)$row['deposit_value']) ?></td><td><a class="ghost-link" href="<?= e(APP_URL) ?>/modules/fieldora/service_edit.php?id=<?= (int)$row['id'] ?>">Edit</a></td></tr><?php endforeach; ?><?php endif; ?></tbody></table></section>
<?php fieldora_layout_end();
